/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/disaster-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List disaster areas
         * @description 取得所有災區清單 (含中心座標) 。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 單頁筆數 (預設 50, 上限 200) */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description 起始位移 (用於分頁) */
                    offset?: components["parameters"]["PageOffset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DisasterArea"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create disaster area
         * @description 新增一筆災區資料。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DisasterArea"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disaster-areas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get disaster area
         * @description 依 ID 取得單一災區。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DisasterArea"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Update disaster area
         * @description 更新災區內容。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DisasterArea"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        /**
         * Delete disaster area
         * @description 刪除指定災區 (需權限)。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List grids
         * @description 取得全部網格 (可於未來加入篩選參數)。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 單頁筆數 (預設 50, 上限 200) */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description 起始位移 (用於分頁) */
                    offset?: components["parameters"]["PageOffset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Grid"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create grid
         * @description 建立新的救援 / 資源網格。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grids/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get grid
         * @description 依 ID 取得單一網格詳情。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Grid"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Update grid
         * @description 更新網格資料 (含需求/狀態)。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        /**
         * Delete grid
         * @description 刪除網格 (通常僅管理員使用)。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volunteer-registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List volunteer registrations
         * @description 取得所有志工報名紀錄 (未加分頁僅示範)。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 單頁筆數 (預設 50, 上限 200) */
                    limit?: components["parameters"]["PageLimit"];
                    /** @description 起始位移 (用於分頁) */
                    offset?: components["parameters"]["PageOffset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VolunteerRegistration"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Register volunteer
         * @description 志工報名參與指定網格。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VolunteerRegistration"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volunteer-registrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel volunteer registration
         * @description 取消指定志工報名。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supply-donations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supply donations
         * @description 取得物資捐贈紀錄清單。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplyDonation"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create supply donation
         * @description 建立一筆捐贈物資紀錄。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupplyDonation"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grid-discussions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List grid discussions
         * @description 取得全部網格的留言 (建議未來加入過濾)。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GridDiscussion"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Post discussion message
         * @description 在指定網格張貼留言。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GridDiscussion"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List announcements
         * @description 取得公告列表 (可依時間排序)。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Announcement"][];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create announcement
         * @description 建立一則公告。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volunteers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List volunteers
         * @description 取得志工概觀或公開欄位。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description 取得使用者列表 (需權限)。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description 回傳目前登入的使用者資訊。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/fix-grid-bounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Normalize / repair stored grid bounds
         * @description 批次修正網格邊界 (僅管理維運)。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Done */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/export-grids-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export grids as CSV
         * @description 匯出所有網格資料為 CSV 檔。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/import-grids-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import grids from CSV content
         * @description 從 CSV 內容匯入 / 更新網格。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        csv: string;
                    };
                };
            };
            responses: {
                /** @description Import result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/grid-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download blank grid template CSV
         * @description 下載空白網格匯入範本。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/external-grid-api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy / external grid API call
         * @description 代理對外部網格系統的呼叫。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions/external-volunteer-api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy / external volunteer API call
         * @description 代理對外部志工系統的呼叫。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync legacy data (v2)
         * @description 與舊版系統同步資料 (可能為非同步背景作業)。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get roster (v2)
         * @description 取得舊系統格式之 roster 資料。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 唯一識別字串 (UUID、ULID 或資料庫主鍵)
         * @example grid_01HZYQ9W123ABCDEF
         */
        ID: string;
        /**
         * Format: date-time
         * @description ISO 8601 時間戳記 (UTC)
         * @example 2025-10-02T08:12:30Z
         */
        Timestamp: string;
        DisasterArea: {
            id: components["schemas"]["ID"];
            /**
             * @description 災區名稱
             * @example 光復鄉重災區
             */
            name: string;
            /**
             * Format: double
             * @description 災區中心點緯度
             * @example 23.8751
             */
            center_lat: number;
            /**
             * Format: double
             * @description 災區中心點經度
             * @example 121.578
             */
            center_lng: number;
            created_at?: components["schemas"]["Timestamp"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        SupplyNeed: {
            /**
             * @description 需求物資名稱
             * @example 鋤頭
             */
            name: string;
            /**
             * @description 需求總數量
             * @example 20
             */
            quantity: number;
            /**
             * @description 數量單位
             * @example 支
             */
            unit: string;
            /**
             * @description 已收到的數量
             * @default 0
             * @example 5
             */
            received: number;
        };
        Grid: {
            id: components["schemas"]["ID"];
            /**
             * @description 網格代碼 (在災區中應唯一)
             * @example A-3
             */
            code: string;
            /**
             * @description 網格類型 (決定使用情境)
             * @example manpower
             * @enum {string}
             */
            grid_type: "mud_disposal" | "manpower" | "supply_storage" | "accommodation" | "food_area";
            disaster_area_id: components["schemas"]["ID"];
            /**
             * @description 需要志工數量 (僅 manpower 類型有意義)
             * @default 0
             * @example 10
             */
            volunteer_needed: number;
            /**
             * @description 已報名志工數量
             * @default 0
             * @example 4
             */
            volunteer_registered: number;
            /**
             * @description 集合地點描述
             * @example 光復國小正門
             */
            meeting_point?: string | null;
            /**
             * @description 風險或安全注意事項
             * @example 地面濕滑，注意積水與電線
             */
            risks_notes?: string | null;
            /**
             * @description 格主或聯絡人資訊 (手機/Line)
             * @example 0912-345-678
             */
            contact_info?: string | null;
            /**
             * Format: double
             * @description 中心點緯度
             * @example 23.87525
             */
            center_lat: number;
            /**
             * Format: double
             * @description 中心點經度
             * @example 121.57812
             */
            center_lng: number;
            /** @description 粗略網格邊界 (地圖顯示用) */
            bounds: {
                /** @example 23.876 */
                north: number;
                /** @example 23.874 */
                south: number;
                /** @example 121.579 */
                east: number;
                /** @example 121.577 */
                west: number;
            };
            /**
             * @description 網格狀態
             * @default open
             * @example open
             * @enum {string}
             */
            status: "open" | "closed" | "completed" | "pending";
            /**
             * @description 所需物資列表
             * @example [
             *       {
             *         "name": "鋤頭",
             *         "quantity": 20,
             *         "unit": "支",
             *         "received": 5
             *       },
             *       {
             *         "name": "工作用手套",
             *         "quantity": 50,
             *         "unit": "副",
             *         "received": 10
             *       }
             *     ]
             */
            supplies_needed?: components["schemas"]["SupplyNeed"][];
            grid_manager_id?: components["schemas"]["ID"];
            created_at?: components["schemas"]["Timestamp"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        VolunteerRegistration: {
            id: components["schemas"]["ID"];
            grid_id: components["schemas"]["ID"];
            user_id: components["schemas"]["ID"];
            created_at?: components["schemas"]["Timestamp"];
        };
        SupplyDonation: {
            id: components["schemas"]["ID"];
            grid_id: components["schemas"]["ID"];
            /**
             * @description 捐贈物資名稱
             * @example 礦泉水
             */
            name: string;
            /**
             * @description 捐贈數量
             * @example 100
             */
            quantity: number;
            /**
             * @description 單位
             * @example 箱
             */
            unit: string;
            /**
             * @description 捐贈者聯絡方式
             * @example water-donor@example.com
             */
            donor_contact?: string;
            created_at?: components["schemas"]["Timestamp"];
        };
        GridDiscussion: {
            id: components["schemas"]["ID"];
            grid_id: components["schemas"]["ID"];
            user_id: components["schemas"]["ID"];
            /**
             * @description 留言內容
             * @example 今天下午 2 點再集中一次清運。
             */
            content: string;
            created_at?: components["schemas"]["Timestamp"];
        };
        Announcement: {
            id: components["schemas"]["ID"];
            /**
             * @description 公告標題
             * @example 10/3 志工集合時間調整
             */
            title: string;
            /**
             * @description 公告內容 (Markdown 可選)
             * @example 明日集合時間改為 **08:30**，請提早 10 分鐘報到。
             */
            body: string;
            created_at?: components["schemas"]["Timestamp"];
        };
        User: {
            id: components["schemas"]["ID"];
            /**
             * @description 使用者顯示名稱
             * @example 林志工
             */
            name?: string;
            /**
             * Format: email
             * @description 使用者電子郵件
             * @example volunteer@example.org
             */
            email?: string;
        };
        Error: {
            /**
             * @description 錯誤訊息
             * @example 未授權的請求
             */
            message: string;
            /**
             * @description 內部錯誤代碼 (可選)
             * @example AUTH_REQUIRED
             */
            code?: string;
        };
    };
    responses: {
        /** @description 未授權 (需要 Bearer Token) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 找不到資源 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 請求參數或內容驗證失敗 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 伺服器內部錯誤 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 單頁筆數 (預設 50, 上限 200) */
        PageLimit: number;
        /** @description 起始位移 (用於分頁) */
        PageOffset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
